#!/usr/bin/env python

import json

import yaml


def main():
    with open('variables.yml', 'r') as f:
        variables = yaml.load(f)

    hostname = variables['env']['hostname']
    inventory = {
        'target': {
            'hosts': [hostname]
        },
        '_meta': {
            'hostvars': {
                hostname: variables
            }
        }
    }

    print(json.dumps(inventory))


if __name__ == '__main__':
    main()
