---
- name: Provision for AWS
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Find the default VPC
      local_action:
        module: ec2_vpc_net_facts
        region: ap-northeast-1
        filters:
          isDefault: "true"  # フィルターの値は文字列
